spring:
  temporal:
    connection:
      target: 127.0.0.1:7233
      namespace: default
    workers-auto-discovery:
      packages:
        - com.example

server:
  port: 8081

logging:
  level:
    io.temporal: DEBUG
    com.example: DEBUG
  pattern:
    console: "%d{HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always